#!/usr/bin/env bash

reply=""
[ -e "$1" ] || {
  echo 'No file matches this pattern.'
  exit
}
echo 'Opening '${#@}' files.'
echo ''
for file in "$@"; do
  echo '> '$file
  [[ $reply = "a" ]] || read -n1 -p "Open? [y]|n|a|q " reply
  echo ''
  case $reply in
    n|N) continue;;
    q|Q) exit;;
    a|A) reply="a"
  esac
  xdg-open $file
done
